#!/bin/bash

DOTVMDIR=~/.local/share/dotvm/

list_versions() {
    current=`dotnet --version 2>/dev/null`

    echo "Installed versions: "
    for i in dotnet-sdk-*; do
        version=`echo $i | sed s/dotnet-sdk-//g`
        if [[ $version == $current ]]; then
            echo " * $version"
        else
            echo "   $version"
        fi
    done
}

set_version(){
    if [ ! -d "dotnet-sdk-$1"  ]; then
        echo "version $1 not installed"
        return
    fi

    rm -f dotnet-sdk

    ln -s $DOTVMDIR/dotnet-sdk-$1 dotnet-sdk
}

install(){
    filename=dotnet-sdk-$1-linux-x64.tar.gz

    rm -rf $filename

    curl --progress-bar --fail -L \
        "https://builds.dotnet.microsoft.com/dotnet/Sdk/$1/$filename" \
        -o $filename

    if [ $? -eq 8 ]; then
        echo "$1 version not found"
        return
    fi

    rm -rf dotnet-sdk-$1

    mkdir dotnet-sdk-$1

    tar -xf $filename -C dotnet-sdk-$1
    rm $filename

    rm -f $DOTVMDIR/dotnet-sdk

    ln -s $DOTVMDIR/dotnet-sdk-$1 $DOTVMDIR/dotnet-sdk
}

remove() {
    current=`dotnet --version 2>/dev/null`

    if [[ $current == $1 ]]; then
        rm -rf dotnet-sdk
        echo "warn: current version removed"
    fi
    rm -rf dotnet-sdk-$1
}

CWD=$(pwd)

cd $DOTVMDIR

if [[ $1 == "install" ]]; then
    install $2
elif [[ $1 == "set" ]]; then
    set_version $2
elif [[ $1 == "list" ]]; then
    list_versions
elif [[ $1 == "remove" ]]; then
    remove $2
else
    echo "usage: dotvm <option>"
    echo
    echo "Options:"
    echo "  install <version>    Install a version"
    echo "  set <version>        Set the version to use"
    echo "  list                 List installed versions"
    echo "  remove <version>     Remove a version"
    echo
fi

cd $CWD
